version: '3.8'

services:
  keycloak:
    image: jboss/keycloak:latest
    container_name: "keycloak"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=keycloak-db
      - DB_PORT=5432
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/iam-keycloak-poc-realm.json
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    volumes:
      - ./iam-keycloak-poc-realm.json:/opt/jboss/keycloak/iam-keycloak-poc-realm.json
    networks:
      - myproject

  iam-app:
    image: "postoronnik/iam-app:v7"
    container_name: "iam-app"
    ports:
      - "8081:8081"
    environment:
      - KEYCLOAK_JWK_SET_URI=http://keycloak:8080/auth/realms/iam-keycloak-poc/protocol/openid-connect/certs
      - JDBC_URL=jdbc:postgresql://db/app
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
    depends_on:
      - app-db
      - keycloak
    networks:
      - myproject
    links:
      - keycloak

  keycloak-db:
    image: postgres:latest
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - myproject

  app-db:
    image: postgres:latest
    container_name: "db"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - app-db-data:/var/lib/postgresql/app/data
    networks:
      - myproject

volumes:
  keycloak-db-data:
  app-db-data:

networks:
  myproject:
    driver: bridge