version: '3.8'

services:
  keycloak:
    image: jboss/keycloak:latest
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=keycloak-db
      - DB_PORT=5432
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/iam-keycloak-poc-realm.json
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    volumes:
      - ./iam-keycloak-poc-realm.json:/opt/jboss/keycloak/iam-keycloak-poc-realm.json

  keycloak-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

volumes:
  keycloak-db-data:
